/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomSlugRouteImport } from './routes/room.$slug'
import { Route as PokerSlugRouteImport } from './routes/poker.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugRoute = RoomSlugRouteImport.update({
  id: '/room/$slug',
  path: '/room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PokerSlugRoute = PokerSlugRouteImport.update({
  id: '/poker/$slug',
  path: '/poker/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poker/$slug': typeof PokerSlugRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poker/$slug': typeof PokerSlugRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poker/$slug': typeof PokerSlugRoute
  '/room/$slug': typeof RoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/poker/$slug' | '/room/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/poker/$slug' | '/room/$slug'
  id: '__root__' | '/' | '/poker/$slug' | '/room/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokerSlugRoute: typeof PokerSlugRoute
  RoomSlugRoute: typeof RoomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug': {
      id: '/room/$slug'
      path: '/room/$slug'
      fullPath: '/room/$slug'
      preLoaderRoute: typeof RoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poker/$slug': {
      id: '/poker/$slug'
      path: '/poker/$slug'
      fullPath: '/poker/$slug'
      preLoaderRoute: typeof PokerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokerSlugRoute: PokerSlugRoute,
  RoomSlugRoute: RoomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
